apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: changewatch-ingress
  namespace: changewatch
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://192.168.1.90:31092/api/authz/forward-auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.madebysteven.nl?rm=$request_method"
    nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
spec:
  ingressClassName: nginx
  rules:
    - host: changewatch.madebysteven.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: changewatch
                port:
                  number: 80
