apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changewatch-data
  namespace: changewatch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeName: changewatch-pv
